let Contain = [
  {
    id: 1,
    image: './images/LandingPage3.png',
    name: 'SinglePay',
    category: 'Landing Page',
    links: 'https://ephemeral-banoffee-e55edd.netlify.app',
  },
  {
    id: 2,
    image: './images/Templates1.png',
    name: 'Flux Game Store',
    category: 'Templates',
    links: 'https://nilesh01011.github.io/flux-game-store',
  },
  {
    id: 3,
    image: './images/E-commerce.png',
    name: 'WishBin',
    category: 'E-commerce',
    links: 'https://wishbin-store.herokuapp.com/',
  },
  {
    id: 4,
    image: './images/Templates.png',
    name: 'M-Movies',
    category: 'Templates',
    links: 'https://nilesh01011.github.io/Movies',
  },
  {
    id: 5,
    image: './images/LandingPage1.png',
    name: '&Gaming',
    category: 'Landing Page',
    links: 'https://nilesh01011.github.io/-Gaming',
  },
  {
    id: 6,
    image: './images/LandingPage.png',
    name: 'OnePlus',
    category: 'Landing Page',
    links: 'https://nilesh01011.github.io/oneplus-store',
  },
  {
    id: 7,
    image: './images/Templates2.png',
    name: 'Admin Dashbord',
    category: 'Templates',
    links: 'https://nilesh01011.github.io/ModernDashBoard',
  },
  {
    id: 8,
    image: './images/Templates3.png',
    name: 'CRUD Blogs',
    category: 'Templates',
    links: 'https://peaceful-horse-f44d71.netlify.app',
  },
  {
    id: 9,
    image: './images/LandingPage2.png',
    name: 'Best Eats',
    category: 'Landing Page',
    links: 'https://shiny-cajeta-c89474.netlify.app',
  },
  {
    id: 10,
    image: './images/Clone.png',
    name: 'Amazon Clone',
    category: 'Clone',
    links: 'https://nilesh01011.github.io/amazonClone',
  },
  {
    id: 11,
    image: './images/Chatapp.png',
    name: 'Chat-It',
    category: 'Chat-App',
    links: 'https://mernchatit.herokuapp.com',
  },
  {
    id: 12,
    image: './images/E-commerce2.png',
    name: 'Proshop',
    category: 'E-commerce',
    links: 'https://proshop-stores.herokuapp.com/',
  },
];

export default Contain;
